const STORE = "pujja.v1";
function load(){try{return JSON.parse(localStorage.getItem(STORE))||{};}catch{return{};}}
function save(s){localStorage.setItem(STORE,JSON.stringify(s));}
function defaultState(){return{xp:0,streak:0,lastDay:null,done:{},hearts:5,page:"home"};}
let S=Object.assign(defaultState(),load());
function today(){return new Date().toISOString().slice(0,10);}
function bumpStreak(){const t=today();if(S.lastDay===t)return;const y=new Date();y.setDate(y.getDate()-1);const ys=y.toISOString().slice(0,10);S.streak=S.lastDay===ys?(S.streak||0)+1:1;S.lastDay=t;}
function doneCount(){return Object.keys(S.done).length;}
function totalLessons(){return (window.LESSONS||[]).length;}
function speak(text){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=0.92;speechSynthesis.speak(u);}
function gardenSVG(){const n=doneCount();const on=lvl=>n>=lvl?"":"locked-layer";return `<svg viewBox="0 0 360 200" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><ellipse cx="180" cy="175" rx="150" ry="16" fill="#0b1a12"/><g class="grow ${on(1)}"><circle cx="60" cy="150" r="18" fill="#2f7a45"/><circle cx="78" cy="148" r="14" fill="#3d9154"/></g><g class="grow ${on(2)}"><rect x="168" y="110" width="8" height="55" fill="#6b4a2a"/><circle cx="172" cy="100" r="28" fill="#2f8a4e"/><circle cx="156" cy="108" r="16" fill="#3da35c"/></g><g class="grow ${on(3)}"><circle cx="250" cy="148" r="16" fill="#c45c3a"/><circle cx="266" cy="146" r="12" fill="#d9784e"/></g><g class="grow ${on(4)}"><path d="M40 160 Q55 90 70 160" stroke="#6b4a2a" fill="none" stroke-width="4"/><circle cx="48" cy="108" r="7" fill="#e8b84a"/><circle cx="62" cy="96" r="7" fill="#f08a2a"/></g><g class="grow ${on(5)}"><path d="M300 165 L300 95" stroke="#5a3a22" stroke-width="3"/><path d="M300 110 Q280 100 300 95 Q320 100 300 110" fill="#c23b4a"/></g><g class="grow ${on(6)}"><circle cx="120" cy="155" r="10" fill="#7dcc8a"/><circle cx="132" cy="150" r="8" fill="#5bb56a"/></g><g class="grow ${on(7)}"><rect x="210" y="130" width="6" height="35" fill="#5a3a22"/><circle cx="213" cy="124" r="16" fill="#2a6e9a"/></g><g class="grow ${on(8)}"><circle cx="90" cy="70" r="16" fill="#e8b84a" opacity=".85"/></g><g class="grow ${on(9)}"><path d="M140 160 Q180 40 220 160" fill="#1e5a36" opacity=".65"/></g><g class="grow ${on(10)}"><path d="M180 50 L188 72 L212 74 L194 88 L198 112 L180 98 L162 112 L166 88 L148 74 L172 72 Z" fill="#e8b84a"/></g><g class="grow ${on(11)}"><ellipse cx="300" cy="168" rx="28" ry="8" fill="#1a4a6a"/><ellipse cx="300" cy="166" rx="18" ry="5" fill="#2a6e9a"/></g><g class="grow ${on(12)}"><path d="M30 170 L90 170" stroke="#c9a56a" stroke-width="4"/></g><g class="grow ${on(13)}"><circle cx="320" cy="60" r="4" fill="#f4efe4"/></g><g class="grow ${on(14)}"><path d="M240 70 Q250 55 265 70 Q250 62 240 70" fill="#e8b84a"/></g><g class="grow ${on(15)}"><circle cx="180" cy="28" r="6" fill="#f4efe4"/></g></svg>`;}
function topbar(){return `<header class="topbar"><div class="brand"><div class="logo">पू</div><div><h1>Pujjaneya Angrezi</h1><p>बातचीत का आत्मविश्वास</p></div></div><div class="stats"><div class="pill">🔥 ${S.streak||0}</div><div class="pill">⭐ ${S.xp||0}</div></div></header>`;}
function home(){let locked=false;const cards=window.LESSONS.map(L=>{const isDone=!!S.done[L.id];const isLocked=locked&&!isDone;if(!isDone)locked=true;return `<article class="lesson ${isDone?"done":""} ${isLocked?"locked":""}" data-id="${L.id}" data-locked="${isLocked}"><div class="badge">${isDone?"✓":L.emoji}</div><div><div class="hi">${L.titleHi}</div><h3>${L.title}</h3></div><div class="xp">${L.xp} XP</div></article>`;}).join("");const n=doneCount();const tot=totalLessons();const cap=n===0?"बगीचा अभी सोया है। पहला पाठ पूरा करें।":n>=tot?"पूरा चित्र जाग उठा।":`${n}/${tot} अंश खुले।`;return `${topbar()}<div class="hero-art">${gardenSVG()}<div class="hero-caption">${cap}</div></div><section class="section"><h2>आपका मार्ग</h2><p class="lede">शब्द आते हैं। अब पूरे पैराग्राफ बोलने की आदत डालें।</p><div class="path">${cards}</div></section>${tabbar("home")}`;}
function practiceHome(){const done=window.LESSONS.filter(L=>S.done[L.id]);const list=done.length?done.map(L=>`<article class="lesson done" data-id="${L.id}" data-locked="false"><div class="badge">${L.emoji}</div><div><div class="hi">${L.titleHi}</div><h3>दोहराएँ · ${L.title}</h3></div></article>`).join(""):`<p class="lede">पहले कोई पाठ पूरा करें।</p>`;return `${topbar()}<section class="section"><h2>अभ्यास</h2>${list}</section>${tabbar("practice")}`;}
function profile(){return `${topbar()}<section class="section"><h2>आपकी प्रगति</h2><div class="card"><p class="en">${S.xp} XP · ${S.streak} दिन · ${doneCount()}/${totalLessons()} पाठ</p></div><div class="card"><button class="btn ghost" id="reset">प्रगति मिटाएँ</button></div></section>${tabbar("profile")}`;}
function tabbar(on){return `<nav class="tabbar"><button data-nav="home" class="${on==="home"?"on":""}">मार्ग</button><button data-nav="practice" class="${on==="practice"?"on":""}">अभ्यास</button><button data-nav="profile" class="${on==="profile"?"on":""}">प्रगति</button></nav>`;}
let session=null;
function startLesson(id,review){const L=window.LESSONS.find(x=>x.id===id);if(!L)return;session={L,i:0,review:!!review,correct:0,total:L.steps.length,picked:null,order:[],bank:[]};renderLesson();}
function renderLesson(){const{L,i}=session;const step=L.steps[i];const pct=Math.round((i/L.steps.length)*100);let body="";if(!step){renderResult();return;}if(step.type==="read"){body=`<div class="card"><h3>${step.title}</h3><p class="hint">${step.prompt}</p><div class="speak"><button class="icon-btn" id="say">🔊</button></div><p class="en para">${L.paragraph.en}</p><p class="hi-line para">${L.paragraph.hi}</p></div>`;}if(step.type==="mcq"||step.type==="join"){const head=step.type==="join"?`<p class="hint">दो सरल वाक्य → Compound sentence</p><p class="en">${step.a}</p><p class="en">${step.b}</p>${step.hi?`<p class="hi-line">${step.hi}</p>`:""}<p class="hint">${step.q||"सही जोड़ चुनें।"}</p>`:`<p class="en">${step.q}</p>`;body=`<div class="card">${head}<div class="choices">${step.options.map((o,idx)=>`<button class="choice" data-i="${idx}">${o}</button>`).join("")}</div><div id="fb"></div></div>`;}if(step.type==="fill"){body=`<div class="card"><p class="en">${step.q}</p><div class="choices">${step.bank.map(w=>`<button class="choice" data-w="${w}">${w}</button>`).join("")}</div><div id="fb"></div></div>`;}if(step.type==="order"){session.order=[];session.bank=step.items.slice().sort(()=>Math.random()-0.5);body=`<div class="card"><p class="en">${step.q}</p><div class="drop chips" id="built"></div><div class="chips" id="bank"></div><div id="fb"></div></div>`;}if(step.type==="match"){session.left=step.pairs.map((p,i)=>({i,t:p[0]})).sort(()=>Math.random()-.5);session.right=step.pairs.map((p,i)=>({i,t:p[1]})).sort(()=>Math.random()-.5);session.selL=null;session.matched=new Set();body=`<div class="card"><p class="en">जोड़ी मिलाएँ</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><div id="colL"></div><div id="colR"></div></div><div id="fb"></div></div>`;}if(step.type==="speak"){body=`<div class="card"><p class="en">${step.q}</p><p class="en para">${L.paragraph.en}</p><p class="hi-line">${L.paragraph.hi}</p><div class="speak"><button class="icon-btn" id="say">🔊</button></div></div>`;}document.getElementById("app").innerHTML=`<div class="screen"><button class="back" id="back">← वापस</button><div class="progress-bar"><i style="width:${pct}%"></i></div>${body}</div><div class="cta-row"><button class="btn" id="next">${step.type==="read"||step.type==="speak"?"आगे बढ़ें":"जाँचें"}</button></div>`;bindLesson(step);}
function bindLesson(step){document.getElementById("back").onclick=()=>{session=null;go("home");};const say=document.getElementById("say");if(say)say.onclick=()=>speak(session.L.paragraph.en);if(step.type==="mcq"||step.type==="join"){document.querySelectorAll(".choice").forEach(b=>{b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");session.picked=+b.dataset.i;};});}if(step.type==="fill"){document.querySelectorAll(".choice").forEach(b=>{b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");session.picked=b.dataset.w;};});}if(step.type==="order")drawOrder(step);if(step.type==="match")drawMatch(step);document.getElementById("next").onclick=()=>check(step);}
function drawOrder(step){const built=document.getElementById("built");const bank=document.getElementById("bank");built.innerHTML=session.order.map((t,i)=>`<button class="chip on" data-from="built" data-i="${i}">${t}</button>`).join("");bank.innerHTML=session.bank.map((t,i)=>`<button class="chip" data-from="bank" data-i="${i}">${t}</button>`).join("");[...built.querySelectorAll("button"),...bank.querySelectorAll("button")].forEach(b=>{b.onclick=()=>{const from=b.dataset.from;const i=+b.dataset.i;if(from==="bank")session.order.push(session.bank.splice(i,1)[0]);else session.bank.push(session.order.splice(i,1)[0]);drawOrder(step);};});}
function drawMatch(step){const L=document.getElementById("colL");const R=document.getElementById("colR");L.innerHTML=session.left.map(x=>`<button class="choice ${session.selL===x.i?"selected":""} ${session.matched.has(x.i)?"good":""}" data-side="L" data-i="${x.i}" ${session.matched.has(x.i)?"disabled":""}>${x.t}</button>`).join("");R.innerHTML=session.right.map(x=>`<button class="choice ${session.matched.has(x.i)?"good":""}" data-side="R" data-i="${x.i}" ${session.matched.has(x.i)?"disabled":""}>${x.t}</button>`).join("");document.querySelectorAll("#colL .choice, #colR .choice").forEach(b=>{b.onclick=()=>{const side=b.dataset.side;const i=+b.dataset.i;if(side==="L"){session.selL=i;drawMatch(step);return;}if(session.selL==null)return;if(session.selL===i){session.matched.add(i);session.selL=null;drawMatch(step);if(session.matched.size===step.pairs.length){fb(true,"सही");session.ready=true;}}else{fb(false,"गलत");session.selL=null;drawMatch(step);}};});}
function fb(ok,msg){const el=document.getElementById("fb");if(!el)return;el.innerHTML=`<div class="feedback ${ok?"ok":"no"}">${msg}</div>`;}
function check(step){if(step.type==="read"||step.type==="speak"){session.correct++;session.i++;renderLesson();return;}let ok=false;if(step.type==="mcq"||step.type==="join")ok=session.picked===step.answer;if(step.type==="fill")ok=session.picked===step.answer;if(step.type==="order")ok=JSON.stringify(session.order)===JSON.stringify(step.items);if(step.type==="match")ok=session.matched&&session.matched.size===step.pairs.length;if(!ok){fb(false,"एक बार और सोचें।");return;}session.correct++;session.i++;renderLesson();}
function renderResult(){const{L,correct,total,review}=session;const xp=review?Math.round(L.xp/3):L.xp;if(!review)S.done[L.id]=true;S.xp+=xp;bumpStreak();save(S);document.getElementById("app").innerHTML=`<div class="screen result"><div class="big">${L.emoji}</div><h2>बहुत अच्छा</h2><p class="hi-line">${L.titleHi} पूरा। +${xp} XP</p><div class="hero-art">${gardenSVG()}</div></div><div class="cta-row"><button class="btn" id="home">मार्ग</button></div>`;document.getElementById("home").onclick=()=>{session=null;go("home");};}
function go(page){S.page=page;const app=document.getElementById("app");if(page==="home")app.innerHTML=home();if(page==="practice")app.innerHTML=practiceHome();if(page==="profile")app.innerHTML=profile();bindNav();}
function bindNav(){document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>go(b.dataset.nav));document.querySelectorAll(".lesson").forEach(el=>{el.onclick=()=>{if(el.dataset.locked==="true")return;startLesson(el.dataset.id,S.page==="practice");};});const r=document.getElementById("reset");if(r)r.onclick=()=>{S=defaultState();save(S);go("profile");};}
go("home");
